# Generated by Django 3.2.3 on 2023-08-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('id',), 'verbose_name': 'подписка', 'verbose_name_plural': 'подписки'},
        ),
    ]
